#! /bin/sh

xss-lock -- betterlockscreen -l blur &
wal -R
killall -q polybar
sxhkd &
polybar main &
flameshot &
compton -b --config ~/.config/compton/compton.conf
dunst &
nm-applet &
blueman-applet &
# feh --bg-fill ~/Pictures/wallpaper.jpg
keepassxc &
pgrep firefox || firefox &
discord &
protonmail-bridge --no-window &
thunderbird &


bspc monitor -d main web chat mail other

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Thunderbird desktop='^4'

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
